import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { PrimeReactProvider, PrimeReactContext } from 'primereact/api';      
import "./globals.css";
import SideNav from "./Components/NavBar";
import 'primereact/resources/primereact.css';
import 'primereact/resources/themes/lara-light-indigo/theme.css';
import "primeicons/primeicons.css";
        
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <PrimeReactProvider>
      <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased md:mt-32 md:mx-auto md:max-w-400`}
      >
        <div className="flex min-h-screen bg-black">
          <SideNav />
          <main className="flex-1">{children}</main>
        </div>
      </body>
    </html>
    </PrimeReactProvider>
    
  );
}
